const express = require('express');
const router = express.Router();

const authRoutes = require('./auth-routes');
const blogRoutes = require('./blog-routes');
const expenseCategoryRoutes = require('./expense-category-routes');
const expenseRoutes = require('./expense-routes');
const departmentRoutes = require('./department-routes');
const divisionMasterRoutes = require('./division-master-routes');
const customerMasterRoutes = require('./customer-master-routes');
const customerTypeMasterRoutes = require('./customer-type-master-routes');
const orderRoutes = require('./order-routes');
const employeeMasterRoutes = require('./employee-master-routes');
const enquiryRoutes = require('./enquiry-routes');
const newsletterRoutes = require('./newsletter-routes');
const callEntryFormRoutes = require('./call-entry-form-routes');
const statusMasterRoutes = require('./status-master-routes');
const callMasterRoutes = require('./call-master-routes');
const callTypeMasterRoutes = require('./call-type-master-routes');
const venderMasterRoutes = require('./vender-master-routes');
const callUrgencyRoutes = require('./call-urgency-routes');
const problemRoutes = require('./problem-routes');
const itemTypeMasterRoutes = require('./item-type-master-routes');
const supportPeriodMasterRoutes = require('./support-period-master-routes');
const designationMasterRoutes = require('./designation-master-routes');
const endUserMasterRoutes = require('./end-user-master-routes');
const callNatureMasterRoutes = require('./call-nature-master-routes');
const instrumentMasterRoutes = require('./instrument-master-routes');
const technicianMasterRoutes = require('./technician-master-routes');

// Register routes
router.use('/auth', authRoutes);
router.use('/blog', blogRoutes);
router.use('/expense-category', expenseCategoryRoutes);
router.use('/expense', expenseRoutes);
router.use('/department', departmentRoutes);
router.use('/division-master', divisionMasterRoutes);
router.use('/customer-master', customerMasterRoutes);
router.use('/customer-type-master', customerTypeMasterRoutes);
router.use('/order', orderRoutes);
router.use('/employee-master', employeeMasterRoutes);
router.use('/enquiry', enquiryRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/call-entry-form', callEntryFormRoutes);
router.use('/status-master', statusMasterRoutes);
router.use('/call-master', callMasterRoutes);
router.use('/call-type-master', callTypeMasterRoutes);
router.use('/vender-master', venderMasterRoutes);
router.use('/call-urgency', callUrgencyRoutes);
router.use('/problem', problemRoutes);
router.use('/item-type-master', itemTypeMasterRoutes);
router.use('/support-period-master', supportPeriodMasterRoutes);
router.use('/designation-master', designationMasterRoutes);
router.use('/end-user-master', endUserMasterRoutes);
router.use('/call-nature-master', callNatureMasterRoutes);
router.use('/instrument-master', instrumentMasterRoutes);
router.use('/technician-master', technicianMasterRoutes);

module.exports = router;
