module.exports = {
    AuthController: require('./auth-controller'),
    BlogController: require('./blog-controller'),
    DepartmentController: require('./department-controller'),
    DivisionMasterController: require('./division-master-controller'),
    CustomerController: require('./customer-master-controller'),
    CustomerTypeMasterController: require('./customer-type-master-controller'),
    ExpenseCategoryController: require('./expense-category-controller'),
    ExpenseController: require('./expense-controller'),
    OrderController: require('./order-controller'),
    EmployeeController: require('./employee-master-controller'),
    EnquiryController: require('./enquiry-controller'),
    CallEntryFormController: require('./call-entry-form-controller'),
    StatusMasterController: require('./status-master-controller'),
    CallMasterController: require('./call-master-controller'),
    CallTypeMasterController: require('./call-type-master-controller'),
    VenderMasterController: require('./vender-master-controller'),
    CallUrgencyController: require('./call-urgency-controller'),
    ProblemController: require('./problem-controller'),
    ItemTypeMasterController: require('./item-type-master-controller'),
    SupportPeriodMasterController: require('./support-period-master-controller'),
    DesignationMasterController: require('./designation-master-controller'),
    EndUserMasterController: require('./end-user-master-controller'),
    CallNatureMasterController: require('./call-nature-master-controller'),
    InstrumentMasterController: require('./instrument-master-controller'),
    TechnicianMasterController: require('./technician-master-controller'),
};
