
module.exports = {
    AuthRepository: require('./auth-repository'),
    CrudRepository: require('./crud-repository'),
    BlogRepository: require('./blog-repository'),
    DepartmentRepository: require('./department-repository'),
    DivisionMasterRepository: require('./division-master-repository'),
    CustomerMasterRepository: require('./customer-master-repository'),
    CustomerTypeMasterRepository: require('./customer-type-master-repository'),
    ExpenseCategoryRepository: require('./expense-category-repository'),
    ExpenseRepository: require('./expense-repository'),
    OrderRepository: require('./order-repository'),
    EmployeeMasterRepository: require('./employee-master-repository'),
    EnquiryRepository: require('./enquiry-repository'),
    CallEntryFormRepository: require('./call-entry-form-repository'),
    StatusMasterRepository: require('./status-master-repository'),
    CallMasterRepository: require('./call-master-repository'),
    CallTypeMasterRepository: require('./call-type-master-repository'),
    VenderMasterRepository: require('./vender-master-repository'),
    CallUrgencyRepository: require('./call-urgency-repository'),
    ProblemRepository: require('./problem-repository'),
    ItemTypeMasterRepository: require('./item-type-master-repository'),
    SupportPeriodMasterRepository: require('./support-period-master-repository'),
    DesignationMasterRepository: require('./designation-master-repository'),
    EndUserMasterRepository: require('./end-user-master-repository'),
    InstrumentMasterRepository: require('./instrument-master-repository'),
    TechnicianMasterRepository: require('./technician-master-repository'),
};
