// ==============================================
// REPORT MODEL
// models/report-model.js
// NAS ERP REPORT + REMINDER SYSTEM
// ==============================================

const mongoose = require("mongoose");

// ==============================================
// DAILY REPORT SCHEMA
// ==============================================
const dailyReportSchema = new mongoose.Schema(
  {
    reportDate: {
      type: Date,
      default: Date.now,
    },

    dailyIncome: {
      type: Number,
      default: 0,
    },

    dailyExpenses: {
      type: Number,
      default: 0,
    },

    dailyProfit: {
      type: Number,
      default: 0,
    },
  },
  { _id: false }
);

// ==============================================
// MONTHLY REPORT SCHEMA
// ==============================================
const monthlyReportSchema = new mongoose.Schema(
  {
    month: {
      type: String,
      required: true,
    },

    year: {
      type: Number,
      required: true,
    },

    monthlySale: {
      type: Number,
      default: 0,
    },

    monthlyProfit: {
      type: Number,
      default: 0,
    },

    monthlyDue: {
      type: Number,
      default: 0,
    },
  },
  { _id: false }
);

// ==============================================
// YEARLY REPORT SCHEMA
// ==============================================
const yearlyReportSchema = new mongoose.Schema(
  {
    year: {
      type: Number,
      required: true,
    },

    annualBusinessReport: {
      type: Number,
      default: 0,
    },

    growthAnalysis: {
      type: String,
      default: "",
    },

    yearlyProfit: {
      type: Number,
      default: 0,
    },

    yearlyExpense: {
      type: Number,
      default: 0,
    },

    yearlyDue: {
      type: Number,
      default: 0,
    },
  },
  { _id: false }
);

// ==============================================
// REMINDER SCHEMA
// ==============================================
const reminderSchema = new mongoose.Schema(
  {
    reminderType: {
      type: String,
      enum: ["WhatsApp", "SMS", "Email"],
      required: true,
    },

    title: {
      type: String,
      required: true,
    },

    message: {
      type: String,
      required: true,
    },

    receiverName: {
      type: String,
      default: "",
    },

    mobileNumber: {
      type: String,
      default: "",
    },

    email: {
      type: String,
      default: "",
    },

    status: {
      type: String,
      enum: ["Pending", "Sent", "Failed"],
      default: "Pending",
    },

    sentAt: {
      type: Date,
    },
  },
  { _id: false }
);

// ==============================================
// MAIN REPORT SCHEMA
// ==============================================
const reportSchema = new mongoose.Schema(
  {
    reportId: {
      type: String,
      unique: true,
    },

    // ==========================================
    // DAILY REPORT
    // ==========================================
    dailyReport: dailyReportSchema,

    // ==========================================
    // MONTHLY REPORT
    // ==========================================
    monthlyReport: monthlyReportSchema,

    // ==========================================
    // YEARLY REPORT
    // ==========================================
    yearlyReport: yearlyReportSchema,

    // ==========================================
    // REMINDERS
    // ==========================================
    reminders: [reminderSchema],

    // ==========================================
    // AUTO GENERATED REPORT
    // ==========================================
    autoGenerated: {
      type: Boolean,
      default: true,
    },

    generatedBy: {
      type: String,
      default: "SYSTEM",
    },

    notes: {
      type: String,
      default: "",
    },
  },
  {
    timestamps: true,
  }
);

// ==============================================
// AUTO REPORT ID GENERATION
// ==============================================
reportSchema.pre("save", async function (next) {
  try {
    if (!this.reportId) {
      const count =
        await mongoose.models.Report.countDocuments();

      this.reportId =
        "RPT-" +
        String(count + 1).padStart(5, "0");
    }

    next();
  } catch (error) {
    next(error);
  }
});

// ==============================================
// EXPORT MODEL
// ==============================================
module.exports = mongoose.model(
  "Report",
  reportSchema
);